# -*- coding: utf-8 -*-
"""Datos de productos Insumos Pop (fuente: Catalogo_Insumos_Pop_ES.pdf)."""

import os

WA = "573018656016"
WA_DISPLAY = "+57 301 8656016"

# Dominio del sitio. Se puede cambiar sin tocar el código:
#   - En local:  SITE_URL=https://otrodominio.com python3 build.py
#   - En CI:     definir la variable de entorno SITE_URL (ver README)
# El dominio de producción actual es insumospop.co.
SITE = os.environ.get("SITE_URL", "https://insumospop.co").rstrip("/")
DOMAIN = SITE.replace("https://", "").replace("http://", "")

POWDERS = [
    dict(
        slug="polvo-taro",
        name="Polvo de Taro",
        short="Taro",
        zh="芋頭",
        price=95000, format="Bolsa 1 kg", grams=1000,
        sku="IP-TARO-1K",
        img="polvo-taro-bubble-tea",
        alt="Bolsa negra de 1 kg de polvo de taro Insumos Pop junto a un plato con polvo violeta",
        origin="Taiwán",
        uses=["Milk tea", "Frappés", "Postres", "Helados"],
        teaser="Polvo de taro para preparar milk tea, frappés, helados y postres con perfil dulce y cremoso.",
        desc=[
            "Mezcla de taro de perfil dulce y cremoso para bebidas frías o calientes. Aporta el color violeta característico y funciona como base de milk tea o frappé.",
            "La bolsa de 1 kg permite estandarizar la receta por gramos. Solicita la ficha técnica para definir la dosis según el tamaño de vaso, la leche y el nivel de dulzor de tu carta.",
        ],
        faqs=[
            ("¿Necesito añadir color violeta a la bebida?",
             "No. El producto aporta el tono violeta de la preparación; revisa la ficha técnica si necesitas conocer su composición completa."),
            ("¿Sirve para bebidas frías y calientes?",
             "Sí. Funciona en milk tea frío o caliente, frappés licuados y bases para postre."),
        ],
        recipes=["bubble-tea-de-taro"],
        related=["polvo-okinawa-brown-sugar", "polvo-coral-azul", "polvo-hokkaido-milk-tea"],
    ),
    dict(
        slug="polvo-okinawa-brown-sugar",
        name="Okinawa Brown Sugar",
        short="Okinawa Brown Sugar",
        zh="黑糖",
        price=95000, format="Bolsa 1 kg", grams=1000,
        sku="IP-OKBS-1K",
        img="polvo-okinawa-brown-sugar",
        alt="Bolsa de 1 kg de polvo Okinawa Brown Sugar Insumos Pop con azúcar moreno en un plato",
        origin="Taiwán (estilo Okinawa, Japón)",
        uses=["Tiger sugar / milk tea", "Toppings", "Frappés", "Postres"],
        teaser="Mezcla de brown sugar para milk tea, frappés y preparaciones estilo tiger con notas de caramelo y melaza.",
        desc=[
            "Perfil de azúcar moreno con notas tostadas, de caramelo y melaza. Puede usarse como base de milk tea o para preparar un jarabe espeso que marque las paredes del vaso.",
            "Estandariza la cantidad de polvo y agua del jarabe antes del servicio. Así puedes repetir el sabor y calcular el costo real de cada bebida.",
        ],
        faqs=[
            ("¿Con este polvo logro el efecto de vetas del tiger sugar?",
             "Sí. Preparado como jarabe espeso permite marcar las vetas doradas en las paredes del vaso antes de servir la leche."),
            ("¿Reemplaza el azúcar de la receta?",
             "Aporta dulzor y sabor a la vez, así que normalmente reduce o reemplaza el endulzante de la bebida."),
        ],
        recipes=["brown-sugar-milk-tea"],
        related=["polvo-taro", "polvo-hokkaido-milk-tea", "polvo-thai-milk-tea"],
    ),
    dict(
        slug="polvo-matcha-taiwan",
        name="Taiwan Matcha",
        short="Matcha",
        zh="抹茶",
        price=95000, format="Bolsa 1 kg", grams=1000,
        sku="IP-MATT-1K",
        img="polvo-matcha-taiwan",
        alt="Bolsa de 1 kg de polvo Taiwan Matcha Insumos Pop con polvo verde intenso en un plato",
        origin="Taiwán",
        uses=["Matcha latte", "Frappés", "Repostería", "Helados"],
        teaser="Mezcla lista de matcha para servicio rápido en lattes, frappés, helados y repostería.",
        desc=[
            "Mezcla sabor matcha pensada para bebidas de preparación rápida. Su perfil herbal y cremoso funciona en lattes fríos o calientes, frappés y postres.",
            "A diferencia del Shizuoka Matcha puro, esta referencia ya está formulada para bebidas. Es una opción práctica cuando la velocidad y la consistencia del servicio pesan más que el control total de la receta.",
        ],
        faqs=[
            ("¿Cuál es la diferencia con el Shizuoka Matcha?",
             "Este es una mezcla lista para bebidas, pensada para servir rápido y con costo controlado. El Shizuoka Matcha es matcha 100% puro de origen japonés, para propuestas de autor."),
            ("¿Funciona en repostería?",
             "Sí. Aporta color y sabor a bizcochos, cheesecakes, cremas y helados."),
        ],
        recipes=["matcha-latte-frio"],
        related=["matcha-shizuoka", "polvo-hojicha", "polvo-cheese-foam"],
    ),
    dict(
        slug="matcha-shizuoka",
        name="Shizuoka Matcha 100% puro",
        short="Shizuoka Matcha",
        zh="静岡抹茶",
        price=110000, format="Bolsa 500 g", grams=500,
        sku="IP-MASH-500",
        img="matcha-shizuoka-puro",
        alt="Bolsa de 500 g de Shizuoka Matcha puro single origin de Insumos Pop con polvo verde en un plato",
        origin="Shizuoka, Japón (single origin)",
        uses=["Matcha de especialidad", "Lattes de autor", "Repostería premium"],
        teaser="Matcha 100% puro de Shizuoka para lattes de autor, bebidas de especialidad y repostería.",
        desc=[
            "Matcha sin leche ni endulzante añadidos. El barista controla la dosis, la leche, el dulzor y la intensidad para adaptar cada bebida al concepto de la cafetería.",
            "La presentación de 500 g está dirigida a cartas de especialidad y recetas de autor. Para una preparación más rápida y ya balanceada, compara con Taiwan Matcha en mezcla lista.",
        ],
        faqs=[
            ("¿Viene endulzado o con leche en polvo?",
             "No. Es matcha 100% puro single origin: tú controlas el endulzante, la leche y la intensidad."),
            ("¿Para qué tipo de negocio es ideal?",
             "Cafeterías de especialidad y barras que quieren un matcha de autor y una historia de origen real para su carta."),
        ],
        recipes=["matcha-latte-frio"],
        related=["polvo-matcha-taiwan", "hojicha-puro", "polvo-cheese-foam"],
    ),
    dict(
        slug="polvo-coral-azul",
        name="Coral Azul (Blue Coral)",
        short="Coral Azul",
        zh="藍珊瑚",
        price=95000, format="Bolsa 1 kg", grams=1000,
        sku="IP-CORAL-1K",
        img="polvo-coral-azul",
        alt="Bolsa de 1 kg de polvo Blue Coral de Insumos Pop con polvo azul eléctrico en un plato",
        origin="Taiwán",
        uses=["Bebidas visuales", "Limonadas y sodas", "Frappés", "Capas de color"],
        teaser="Polvo para bebidas azules, frappés, limonadas cremosas y preparaciones por capas.",
        desc=[
            "Coral Azul aporta un color azul intenso a bebidas lácteas, frappés y preparaciones frías. También puede combinarse con limonadas o sodas para crear contrastes y capas.",
            "Antes de llevarlo a carta, prueba la dosis en tu vaso y documenta la receta. Esto ayuda a que el color y el sabor se repitan entre turnos y sedes.",
        ],
        faqs=[
            ("¿Con qué se combina mejor?",
             "Con bases lácteas, limonadas, sodas y frappés. También funciona en capas para bebidas de dos colores."),
            ("¿El color se mantiene en la bebida?",
             "Sí, entrega un azul estable ideal para fotos y video."),
        ],
        recipes=["soda-italiana-con-sirope"],
        related=["polvo-taro", "polvos-de-fruta", "siropes-de-fruta"],
    ),
    dict(
        slug="polvo-hojicha",
        name="Hojicha",
        short="Hojicha",
        zh="ほうじ茶",
        price=95000, format="Bolsa 1 kg", grams=1000,
        sku="IP-HOJI-1K",
        img="polvo-hojicha",
        alt="Bolsa de 1 kg de polvo Hojicha de Insumos Pop con polvo tostado color caramelo en un plato",
        origin="Taiwán (té verde tostado estilo Japón)",
        uses=["Hojicha latte", "Milk tea", "Frappés", "Postres"],
        teaser="Mezcla lista de hojicha para lattes, milk tea, frappés y postres con perfil tostado.",
        desc=[
            "Mezcla para bebidas con perfil de té tostado y notas que recuerdan al caramelo, la nuez y la madera. Suele resultar más suave y menos vegetal que un matcha latte.",
            "Está formulada para un servicio rápido y consistente. Si tu cafetería busca controlar cada ingrediente, compara con Pure Hojicha 100% puro.",
        ],
        faqs=[
            ("¿Sabe parecido al matcha?",
             "No: es más tostado y dulce en nariz, con menos amargor. Muchos clientes que no disfrutan el matcha aman el hojicha."),
            ("¿Cuál es la diferencia con el Pure Hojicha?",
             "Este es una mezcla lista para bebidas. El Pure Hojicha es té tostado 100% puro para recetas de autor."),
        ],
        recipes=["matcha-latte-frio"],
        related=["hojicha-puro", "polvo-matcha-taiwan", "polvo-hokkaido-milk-tea"],
    ),
    dict(
        slug="hojicha-puro",
        name="Pure Hojicha 100% puro",
        short="Pure Hojicha",
        zh="ほうじ茶",
        price=110000, format="Bolsa 500 g", grams=500,
        sku="IP-HOJP-500",
        img="hojicha-puro-japon",
        alt="Bolsa de 500 g de Pure Hojicha single origin de Insumos Pop con té tostado molido en un plato",
        origin="Japón (single origin)",
        uses=["Lattes de autor", "Postres de especialidad", "Bebidas bajas en cafeína"],
        teaser="Hojicha 100% puro de Japón para lattes, postres y bebidas de autor con perfil tostado.",
        desc=[
            "Té verde tostado molido, sin leche ni endulzante añadidos. Tiene un perfil cálido con notas de caramelo, nuez y madera para lattes y postres.",
            "Al ser puro, permite controlar la dosis y el dulzor de cada receta. La presentación de 500 g está pensada para barras que desarrollan bebidas de autor.",
        ],
        faqs=[
            ("¿Tiene menos cafeína que el matcha?",
             "El hojicha suele contener menos cafeína que el matcha, pero la cantidad exacta depende del producto y de la dosis. Consulta la ficha técnica antes de hacer una afirmación nutricional en tu carta."),
            ("¿Viene endulzado?",
             "No. Es té tostado 100% puro: tú defines leche, endulzante e intensidad."),
        ],
        recipes=["matcha-latte-frio"],
        related=["polvo-hojicha", "matcha-shizuoka", "polvo-okinawa-brown-sugar"],
    ),
    dict(
        slug="polvo-thai-milk-tea",
        name="Thai Milk Tea",
        short="Thai Milk Tea",
        zh="泰式奶茶",
        price=95000, format="Bolsa 1 kg", grams=1000,
        sku="IP-THAI-1K",
        img="polvo-thai-milk-tea",
        alt="Bolsa de 1 kg de polvo Thai Milk Tea de Insumos Pop con polvo naranja vibrante en un plato",
        origin="Taiwán (estilo Tailandia)",
        uses=["Thai tea frío", "Milk tea", "Frappés"],
        teaser="Mezcla de Thai Milk Tea para preparar té frío, milk tea y frappés con perfil dulce y especiado.",
        desc=[
            "Mezcla para bebidas de estilo tailandés, con perfil dulce, cremoso y especiado. Aporta el color naranja característico de este tipo de preparación.",
            "Puede servirse con hielo, leche condensada o leche evaporada. Define una dosis fija para que el dulzor y el color no cambien entre preparaciones.",
        ],
        faqs=[
            ("¿El color naranja es el característico del thai tea?",
             "Sí, entrega el tono naranja icónico del té tailandés tradicional."),
            ("¿Cómo se sirve tradicionalmente?",
             "Frío, con hielo y un toque de leche condensada o evaporada por encima."),
        ],
        recipes=["brown-sugar-milk-tea"],
        related=["polvo-hokkaido-milk-tea", "polvo-taro", "polvo-lemon-condensed-milk"],
    ),
    dict(
        slug="polvo-lemon-condensed-milk",
        name="Taiwan Lemon Condensed Milk",
        short="Lemon Condensed Milk",
        zh="檸檬煉乳",
        price=95000, format="Bolsa 1 kg", grams=1000,
        sku="IP-LEMON-1K",
        img="polvo-lemon-condensed-milk",
        alt="Bolsa de 1 kg de polvo Lemon Condensed Milk de Insumos Pop con polvo amarillo suave en un plato",
        origin="Taiwán",
        uses=["Bebidas cítricas", "Frappés", "Limonadas cremosas"],
        teaser="Mezcla de limón y leche condensada para frappés, bebidas cítricas y limonadas cremosas.",
        desc=[
            "Perfil cítrico y cremoso que combina limón con leche condensada. Está pensado para bebidas frías, frappés y limonadas con mayor cuerpo.",
            "Prueba la mezcla con la leche o base que uses en tu negocio y ajusta la dosis antes de publicarla en carta.",
        ],
        faqs=[
            ("¿Es muy ácido?",
             "No: el perfil es equilibrado, con la cremosidad de la leche condensada suavizando el cítrico."),
            ("¿En qué bebidas funciona mejor?",
             "Limonadas cremosas, frappés y tés fríos con un giro diferente."),
        ],
        recipes=["soda-italiana-con-sirope"],
        related=["polvo-mango-coco-hong-kong", "polvos-de-fruta", "polvo-coral-azul"],
    ),
    dict(
        slug="polvo-hokkaido-milk-tea",
        name="Hokkaido Milk Tea",
        short="Hokkaido Milk Tea",
        zh="北海道奶茶",
        price=95000, format="Bolsa 1 kg", grams=1000,
        sku="IP-HOKK-1K",
        img="polvo-hokkaido-milk-tea",
        alt="Bolsa de 1 kg de polvo Hokkaido Milk Tea de Insumos Pop con polvo cremoso en un plato",
        origin="Taiwán (estilo Hokkaido, Japón)",
        uses=["Milk tea", "Bebidas calientes", "Frappés"],
        teaser="Mezcla de Hokkaido Milk Tea para bebidas frías, calientes y frappés con perfil lácteo suave.",
        desc=[
            "Mezcla estilo Hokkaido de perfil suave, lácteo y cremoso. Puede prepararse fría, caliente o en frappé.",
            "Su sabor familiar la convierte en una referencia sencilla para ampliar una carta. Pide la dosificación recomendada y calcula el costo según tu tamaño de vaso.",
        ],
        faqs=[
            ("¿Es un buen sabor para empezar mi carta?",
             "Sí: es el perfil más familiar y fácil de vender de los milk teas, ideal como puerta de entrada."),
            ("¿Funciona caliente?",
             "Sí. Puede prepararse en bebidas calientes, frías o frappés."),
        ],
        recipes=["brown-sugar-milk-tea"],
        related=["polvo-okinawa-brown-sugar", "polvo-thai-milk-tea", "polvo-taro"],
    ),
    dict(
        slug="polvo-mango-coco-hong-kong",
        name="Hong Kong Mango Coconut",
        short="Mango Coconut",
        zh="芒果椰子",
        price=95000, format="Bolsa 1 kg", grams=1000,
        sku="IP-HKMC-1K",
        img="polvo-mango-coco-hong-kong",
        alt="Bolsa de 1 kg de polvo Hong Kong Mango Coconut de Insumos Pop con polvo dorado en un plato",
        origin="Taiwán (estilo Hong Kong)",
        uses=["Frappés", "Smoothies", "Postres tropicales"],
        teaser="Mezcla de mango y coco para frappés, smoothies, bebidas frías y postres tropicales.",
        desc=[
            "Combina un perfil de mango maduro con coco cremoso. Funciona como base de frappés, smoothies y postres.",
            "También puede mezclarse con fruta fresca o congelada para ajustar intensidad y textura. Estandariza la receta antes del servicio.",
        ],
        faqs=[
            ("¿Sirve para smoothies con fruta natural?",
             "Sí: potencia el sabor y da cuerpo cremoso a smoothies con fruta fresca o congelada."),
            ("¿Qué toppings le van bien?",
             "Perlas de tapioca, jellies de coco o mango y espuma de queso."),
        ],
        recipes=["soda-italiana-con-sirope"],
        related=["polvos-de-fruta", "polvo-lemon-condensed-milk", "siropes-de-fruta"],
    ),
    dict(
        slug="polvo-cheese-foam",
        name="Taiwan Cheese Foam",
        short="Cheese Foam",
        zh="芝士奶蓋",
        price=95000, format="Bolsa 1 kg", grams=1000,
        sku="IP-CHFO-1K",
        img="polvo-cheese-foam",
        alt="Bolsa de 1 kg de polvo Cheese Foam de Insumos Pop con polvo claro en un plato",
        origin="Taiwán",
        uses=["Topping de bebidas", "Té frío", "Café frío", "Frappés"],
        teaser="Mezcla para preparar cheese foam, un topping cremoso y ligeramente salado para té, café y frappés.",
        desc=[
            "Mezcla para una espuma cremosa de queso, dulce y ligeramente salada. Se sirve como capa superior sobre té frío, café, matcha o milk tea.",
            "Requiere batidora o shaker, pero no maquinaria especializada. Define el gramaje por porción para controlar textura, velocidad de preparación y costo.",
        ],
        faqs=[
            ("¿Sobre qué bebidas se sirve?",
             "Sobre té frío (verde, negro, de fruta), café frío, matcha y milk teas. Se sirve como capa superior."),
            ("¿Necesito equipo especial?",
             "Solo batidora o shaker: la espuma se logra batiendo el polvo con leche fría."),
        ],
        recipes=["matcha-latte-frio"],
        related=["polvo-matcha-taiwan", "polvo-okinawa-brown-sugar", "polvo-taro"],
    ),
]

FRUIT_POWDER = dict(
    slug="polvos-de-fruta",
    seo_name="Polvos de fruta para bebidas",
    name="Polvos de Fruta — Sabores Asiáticos",
    short="Polvos de Fruta",
    zh="果粉",
    price=65000, format="Bolsa 1 kg", grams=1000,
    sku="IP-FRUTA-1K",
    img="polvos-de-fruta-linea",
    img2="polvos-de-fruta-sabores",
    alt="Línea de polvos de fruta Insumos Pop: bolsas blancas de mango, fresa, coco y sandía de 1 kg",
    alt2="Bolsas de polvos de fruta de Insumos Pop en sabores mango, fresa, coco y sandía",
    origin="Asia (importación directa)",
    flavors=["Mango", "Fresa", "Coco", "Banana", "Sandía", "Aguacate"],
    uses=["Frappés", "Smoothies", "Milk tea de fruta", "Postres"],
    teaser="Polvos de fruta en seis sabores para frappés, smoothies, milk tea, helados y postres.",
    desc=[
        "Línea en sabores mango, fresa, coco, banana, sandía y aguacate. Cada bolsa contiene 1 kg y puede utilizarse en bebidas o postres.",
        "Puedes combinar varios sabores en una cotización. Antes de comprar volumen, prueba la dosis con la base y el tamaño de vaso de tu operación.",
    ],
    faqs=[
        ("¿Puedo pedir varios sabores en un mismo pedido?",
         "Claro: arma tu cotización con los sabores que necesites; cada bolsa de 1 kg cuesta $65.000 con IVA incluido."),
        ("¿Qué sabores hay disponibles?",
         "Mango, Fresa, Coco, Banana, Sandía y Aguacate."),
    ],
    recipes=["soda-italiana-con-sirope"],
    related=["siropes-de-fruta", "polvo-mango-coco-hong-kong", "polvo-coral-azul"],
)

SYRUP = dict(
    slug="siropes-de-fruta",
    seo_name="Siropes de fruta para bebidas",
    name="Siropes de Fruta — Concentrados Asiáticos",
    short="Siropes de Fruta",
    zh="果露",
    price=110000, format="Botella 1.9 L", grams=None,
    sku="IP-SIROPE-19L",
    img="siropes-de-fruta-linea",
    img2="sirope-melocoton",
    img3="siropes-sabores",
    alt="Línea de siropes de fruta Insumos Pop en botellas de 1.9 litros",
    alt2="Botella de sirope de melocotón de Insumos Pop de 1.9 litros",
    alt3="Botellas de sirope de fruta Insumos Pop de 1.9 litros en varios sabores",
    origin="Taiwán",
    flavors=["Mango", "Maracuyá", "Fresa", "Lychee", "Melocotón", "Piña",
             "Arándano", "Limón", "Naranja", "Toronja", "Cereza", "Manzana Verde"],
    uses=["Cócteles", "Frappés", "Lattes", "Limonadas", "Sodas italianas", "Té de frutas"],
    teaser="Siropes concentrados de fruta en 12 sabores para cócteles, mocktails, sodas, limonadas y té frío.",
    desc=[
        "Concentrados de fruta de Taiwán en botella de 1,9 L. La línea incluye mango, maracuyá, fresa, lychee, melocotón, piña, arándano, limón, naranja, toronja, cereza y manzana verde.",
        "La dosis la define cada barra. Con 20 ml por bebida, una botella alcanza para 95 preparaciones y el sirope cuesta cerca de $1.158 por vaso; los demás ingredientes se calculan aparte.",
    ],
    faqs=[
        ("¿Cuántos sabores puedo combinar en un pedido?",
         "Los que quieras: arma tu cotización con los sabores que necesita tu barra."),
        ("¿Sirven para coctelería?",
         "Sí: son concentrados aptos para cóctel, mocktail, soda italiana, limonada, frappé, latte y té de frutas."),
    ],
    recipes=["soda-italiana-con-sirope"],
    related=["polvos-de-fruta", "polvo-coral-azul", "polvo-mango-coco-hong-kong"],
)

RECIPES = [
    dict(
        slug="bubble-tea-de-taro",
        title="Bubble tea de taro",
        metadesc="Receta sugerida de bubble tea de taro paso a paso para tu negocio: base de té, polvo de taro y perlas de tapioca.",
        intro="Receta base para un vaso grande de milk tea de taro. Ajusta la dosis y el dulzor al tamaño de vaso, la leche y el costo objetivo de tu negocio.",
        uses=["polvo-taro"],
        ingredients=[
            "Polvo de Taro Insumos Pop (dosis sugerida: 2–3 cucharadas, ajusta a tu receta)",
            "200 ml de té negro o de jazmín preparado y frío",
            "150 ml de leche entera o bebida vegetal",
            "Hielo al gusto",
            "Perlas de tapioca cocidas",
            "Endulzante al gusto (opcional: el taro ya aporta dulzor)",
        ],
        steps=[
            "Cocina las perlas de tapioca y resérvalas en almíbar para que no se peguen.",
            "En shaker o licuadora, mezcla el té frío, la leche y el polvo de taro hasta disolver por completo.",
            "Prueba y ajusta dulzor. La bebida debe quedar cremosa y de color violeta uniforme.",
            "Sirve las perlas en el vaso, agrega hielo y vierte la mezcla de taro.",
            "Cierra con tapa de cúpula o sella y entrega con un pitillo grueso.",
        ],
        tip="Para versión frappé, licúa la misma mezcla con el hielo y sirve con las perlas al fondo.",
    ),
    dict(
        slug="brown-sugar-milk-tea",
        title="Brown sugar milk tea estilo tigre",
        metadesc="Receta sugerida de brown sugar milk tea (tiger sugar) con vetas doradas, usando polvo Okinawa Brown Sugar.",
        intro="El efecto de vetas se logra preparando un jarabe espeso de brown sugar y cubriendo las paredes del vaso antes de servir la leche.",
        uses=["polvo-okinawa-brown-sugar"],
        ingredients=[
            "Polvo Okinawa Brown Sugar Insumos Pop (para el jarabe: disuelto en un poco de agua caliente hasta espesar)",
            "250 ml de leche entera bien fría",
            "Perlas de tapioca cocidas",
            "Hielo al gusto",
            "Opcional: shot de té negro concentrado",
        ],
        steps=[
            "Prepara un jarabe espeso disolviendo el polvo de brown sugar en muy poca agua caliente.",
            "Mezcla las perlas calientes con parte del jarabe para glasearlas.",
            "Con una cuchara, pinta vetas de jarabe en las paredes internas del vaso.",
            "Agrega las perlas glaseadas, el hielo y vierte la leche fría lentamente.",
            "Sirve sin mezclar para conservar las vetas hasta que el cliente revuelva la bebida.",
        ],
        tip="Sirve inmediatamente después de pintar el vaso para que las vetas se mantengan definidas.",
    ),
    dict(
        slug="matcha-latte-frio",
        title="Matcha latte frío y versión hojicha",
        metadesc="Receta sugerida de matcha latte frío con matcha taiwanés o Shizuoka puro, y variante de hojicha latte.",
        intro="Puedes prepararlo con mezcla lista para un servicio rápido o con matcha puro para controlar la receta. La misma técnica sirve para un hojicha latte.",
        uses=["polvo-matcha-taiwan", "matcha-shizuoka", "polvo-hojicha", "hojicha-puro"],
        ingredients=[
            "Taiwan Matcha Insumos Pop (mezcla lista) o Shizuoka Matcha 100% puro (dosifica según intensidad deseada)",
            "200 ml de leche fría (entera o vegetal)",
            "60 ml de agua caliente (si usas matcha puro, para activar el té)",
            "Endulzante al gusto (el matcha puro no viene endulzado)",
            "Hielo",
        ],
        steps=[
            "Si usas matcha puro: bátelo con el agua caliente (batidor de bambú o eléctrico) hasta que no queden grumos.",
            "Si usas la mezcla lista: disuélvela directamente en un poco de leche.",
            "Llena el vaso con hielo y vierte la leche fría.",
            "Corona vertiendo el matcha por encima para lograr el degradé verde.",
            "Opcional: termina con una capa de Cheese Foam.",
        ],
        tip="Cambia el matcha por Hojicha o Pure Hojicha para ofrecer una versión tostada con la misma técnica base.",
    ),
    dict(
        slug="soda-italiana-con-sirope",
        title="Soda italiana con sirope de fruta",
        metadesc="Receta sugerida de soda italiana y limonada con siropes concentrados de fruta asiáticos: lychee, maracuyá, melocotón y más.",
        intro="Una receta base de soda, hielo y sirope concentrado que también puede adaptarse a limonada, té frío o cócteles.",
        uses=["siropes-de-fruta", "polvos-de-fruta", "polvo-coral-azul"],
        ingredients=[
            "Sirope de fruta Insumos Pop del sabor que quieras (lychee, maracuyá, melocotón, manzana verde…)",
            "Soda o agua con gas bien fría",
            "Hielo",
            "Opcional: jugo de limón, fruta fresca o jellies para decorar",
        ],
        steps=[
            "Llena el vaso con hielo.",
            "Agrega 20 ml de sirope como punto de partida y ajusta después de probar la receta.",
            "Completa con soda fría y decora con fruta o hierbabuena.",
            "Sirve con pitillo y mezcla frente al cliente para conservar el degradé hasta el servicio.",
            "Para limonada: reemplaza la soda por limonada natural. Para el 'trago azul', suma un toque de Coral Azul.",
        ],
        tip="Marca en tu carta los sabores de temporada y rota los siropes para mantener la novedad.",
    ),
]

# ---------------------------------------------------------------- landings por perfil
PROFILES = [
    dict(
        slug="proveedor-bubble-tea",
        catalog_href="polvos-bubble-tea/",
        catalog_label="Ver los polvos",
        label="Tiendas de bubble tea",
        title="Proveedor de insumos para Bubble Tea en Colombia | Insumos Pop",
        metadesc="Polvos de taro, milk tea, brown sugar y toppings para tiendas de bubble tea. Precios con IVA, ficha técnica, muestras y envíos en Colombia.",
        eyebrow="Para tiendas de bubble tea",
        h1="Proveedor de polvos y siropes para bubble tea en Colombia",
        lead="Cotiza taro, milk tea, brown sugar, cheese foam y otros insumos para tu tienda. Consulta precio, dosificación, disponibilidad y envío antes de comprar.",
        cta_label="Cotizar insumos y pedir muestra",
        hero_product="polvo-okinawa-brown-sugar",
        wa_msg="Hola Insumos Pop. Tengo una tienda de bubble tea y quiero cotizar polvos de Taiwán. ¿Me comparten precios por volumen y condiciones de la muestra?",
        trust=[("Precios publicados", "IVA incluido en cada ficha"),
               ("Costo calculable", "Precio por gramo en cada ficha"),
               ("Muestra para negocios", "Prueba con tu propia receta")],
        benefits=[
            ("Información para comparar",
             "Cada ficha muestra presentación, precio, origen, aplicaciones y SKU. Al cotizar compartimos documentación y dosificación."),
            ("Costo por bebida calculable",
             "Bolsas de 1 kg a $95.000: cada ficha muestra el costo por gramo para que calcules tu margen por vaso antes de comprar."),
            ("Pruébalo antes de comprar",
             "Muestra gratis para negocios y asesoría directa: compara color, aroma y disolución contra tu insumo actual con tu propia receta."),
        ],
        product_slugs=["polvo-taro", "polvo-okinawa-brown-sugar", "polvo-thai-milk-tea",
                       "polvo-hokkaido-milk-tea", "polvo-cheese-foam", "polvo-coral-azul"],
        kit=dict(name="Kit Sabores de Taiwán",
                 pitch="Tres bases de milk tea y Cheese Foam para crear cuatro estilos de bebida con una compra inicial.",
                 items=[("polvo-taro", 1, None), ("polvo-okinawa-brown-sugar", 1, None),
                        ("polvo-thai-milk-tea", 1, None), ("polvo-cheese-foam", 1, None)]),
        menu_ideas=["Taro milk tea", "Tiger brown sugar", "Thai tea frío", "Hokkaido clásico",
                    "Bebida fría Coral Azul", "Té frío + cheese foam"],
        recipe_slugs=["bubble-tea-de-taro", "brown-sugar-milk-tea"],
        faqs=[
            ("¿En qué se diferencia de los polvos que ya uso?",
             "Son importados directamente de Taiwán, el país donde nació el bubble tea. Te enviamos muestra gratis para que compares color, aroma y disolución contra tu insumo actual con tu propia receta: la prueba la haces tú."),
            ("¿Cuánto rinde una bolsa de 1 kg?",
             "Depende de tu dosis por vaso. Cada ficha incluye el costo por gramo (a $95.000 el kilo, $95 por gramo) para que calcules el rendimiento exacto con tu receta, y al cotizar te compartimos la ficha técnica con dosificación."),
            ("¿Venden perlas de tapioca o vasos?",
             "Por ahora nuestro catálogo se concentra en polvos, puros y siropes. Al cotizar te asesoramos sobre cómo integrarlos con los demás insumos de tu operación."),
        ],
        extra_html="",
        cta_title="¿Listo para que tu barra sepa a Taiwán?",
        cta_text="Pide tu muestra gratis, compárala con tu insumo actual y decide con tu propia receta.",
    ),
    dict(
        slug="bubble-tea-para-cafeterias",
        catalog_href="polvos-bubble-tea/",
        catalog_label="Ver el catálogo",
        label="Cafeterías",
        title="Matcha, Hojicha y Bubble Tea para Cafeterías | Insumos Pop",
        metadesc="Matcha, hojicha, milk tea y cheese foam para cafeterías. Compara mezclas listas y puros, precios con IVA, muestras y envíos en Colombia.",
        eyebrow="Para cafeterías",
        h1="Matcha, hojicha y toppings para cafeterías en Colombia",
        lead="Elige entre mezclas listas para servicio rápido y productos puros para recetas de autor. Compara formatos, precios y aplicaciones antes de cotizar.",
        cta_label="Cotizar para mi cafetería",
        hero_product="matcha-shizuoka",
        wa_msg="Hola Insumos Pop 👋 Tengo una cafetería y quiero diferenciar mi carta con matcha, hojicha y cheese foam. ¿Me envían cotización y muestra gratis?",
        trust=[("Dos tipos de producto", "Mezclas listas y puros"),
               ("Precios con IVA", "Desde $95.000 por mezcla de 1 kg"),
               ("Prueba y documentación", "Muestra y ficha técnica al cotizar")],
        benefits=[
            ("Dos niveles para tu operación",
             "Mezclas listas ($95.000/kg) para servicio rápido y puros ($110.000/500 g) para bebidas de autor: tú eliges margen y posicionamiento."),
            ("Origen y composición diferenciados",
             "Shizuoka Matcha y Pure Hojicha son referencias puras de Japón; las mezclas de Taiwán están formuladas para preparación rápida."),
            ("Un topping para ampliar la carta",
             "Cheese foam se usa sobre café, té frío, matcha y milk tea. Estandariza la porción para calcular el costo adicional por vaso."),
        ],
        product_slugs=["matcha-shizuoka", "hojicha-puro", "polvo-matcha-taiwan",
                       "polvo-hojicha", "polvo-cheese-foam", "siropes-de-fruta"],
        kit=dict(name="Kit Barra de Especialidad",
                 pitch="Dos productos puros de Japón para bebidas de autor más Cheese Foam como topping.",
                 items=[("matcha-shizuoka", 1, None), ("hojicha-puro", 1, None),
                        ("polvo-cheese-foam", 1, None)]),
        menu_ideas=["Matcha latte de autor", "Hojicha latte", "Dirty matcha", "Café frío con cheese foam",
                    "Soda italiana de temporada", "Matcha tonic"],
        recipe_slugs=["matcha-latte-frio", "soda-italiana-con-sirope"],
        faqs=[
            ("¿Cuál me conviene: el Taiwan Matcha o el Shizuoka puro?",
             "El Taiwan Matcha es mezcla lista para un servicio rápido. El Shizuoka es matcha 100% puro sin endulzar para controlar leche, dulzor e intensidad. Elige según tu operación y el tipo de receta que quieres servir."),
            ("¿Mi barista necesita capacitación o equipo especial?",
             "Necesita herramientas básicas de barra. Las mezclas se disuelven en leche; el matcha puro se bate con agua caliente y el Cheese Foam se prepara con batidora o shaker. Al cotizar compartimos la ficha técnica."),
            ("¿Estas bebidas son moda pasajera?",
             "Ningún proveedor puede garantizar la demanda de tu ciudad. Empieza con una muestra, prueba dos o tres recetas con clientes reales y amplía la compra solo si la rotación y el margen funcionan."),
        ],
        extra_html="""<div class="compare"><h3>¿Mezcla lista o producto puro?</h3>
<p><strong>Mezcla lista:</strong> reduce pasos y facilita que el equipo repita la receta durante horas de alto volumen.</p>
<p><strong>Producto puro:</strong> permite controlar dosis, leche y dulzor para bebidas de autor.</p>
<p class="muted">La mejor opción depende de tu velocidad de servicio, precio de carta y nivel de personalización.</p></div>""",
        cta_title="Prueba qué formato funciona en tu barra",
        cta_text="Cotiza matcha, hojicha o cheese foam y solicita una muestra para evaluarla con tu equipo.",
    ),
    dict(
        slug="kit-emprendedor-bubble-tea",
        catalog_href="guia-emprender-bubble-tea/",
        catalog_label="Leer la guía para emprender",
        label="Emprendedores",
        title="Kit para Empezar un Negocio de Bubble Tea | Insumos Pop",
        metadesc="Kit inicial de polvos y siropes para montar un menú de bubble tea. Precios con IVA, recetas base, muestras, asesoría y envíos en Colombia.",
        eyebrow="Para tu primer negocio",
        h1="Kit de insumos para empezar a vender bubble tea",
        lead="Empieza con un menú corto de polvos y siropes. Revisa el precio del kit, las recetas base y el costo por gramo antes de decidir.",
        cta_label="Empezar con asesoría gratis",
        hero_product="polvo-taro",
        wa_msg="Hola Insumos Pop 👋 Estoy montando mi primer negocio de bebidas y quiero asesoría para armar mi menú inicial. ¿Me ayudan con la cotización del Kit Primer Menú?",
        trust=[("Costos claros", "Costo por gramo antes de invertir"),
               ("Asesoría real", "Un asesor directo por WhatsApp"),
               ("Prueba antes de comprar", "Muestra para negocios y factura")],
        benefits=[
            ("Costos claros antes de invertir",
             "Cada ficha muestra el costo por gramo: sabes cuánto te cuesta cada bebida antes de comprar la primera bolsa."),
            ("Asesoría para tomar decisiones",
             "Te ayudamos a elegir sabores, revisar dosis y adaptar las recetas base al tamaño de vaso de tu negocio."),
            ("Prueba antes de una compra mayor",
             "Puedes solicitar muestra, recibes factura de Taro Pop S.A.S. y puedes ajustar los productos del kit antes de cotizar."),
        ],
        product_slugs=["polvo-taro", "polvo-hokkaido-milk-tea", "polvo-matcha-taiwan",
                       "siropes-de-fruta", "polvos-de-fruta"],
        kit=dict(name="Kit Primer Menú",
                 pitch="Tres bases en polvo y dos siropes para preparar las recetas iniciales de milk tea, lattes, limonadas y sodas del sitio.",
                 items=[("polvo-taro", 1, None), ("polvo-hokkaido-milk-tea", 1, None),
                        ("polvo-matcha-taiwan", 1, None), ("siropes-de-fruta", 2, " — sabores a elección")]),
        menu_ideas=["Taro milk tea", "Milk tea clásico", "Matcha latte frío",
                    "Limonada de sabores", "Soda italiana"],
        recipe_slugs=["bubble-tea-de-taro", "matcha-latte-frio"],
        faqs=[
            ("¿Cuánto necesito para empezar?",
             "El Kit Primer Menú cuesta $505.000 con IVA incluido e incluye 3 bolsas de polvo de 1 kg y 2 siropes de 1,9 L. También puedes cotizar productos sueltos desde $65.000."),
            ("No sé nada de bubble tea, ¿me van a dejar solo?",
             "No. Al cotizar recibes asesoría directa y ficha técnica de cada producto, y en el sitio tienes la guía para emprender y 4 recetas paso a paso con dosis sugeridas."),
            ("¿Me garantizan que el negocio va a funcionar?",
             "No. Las ventas dependen de tu ubicación, precio, ejecución y demanda. Nosotros publicamos precios con IVA, ofrecemos muestras y te ayudamos a calcular el costo del insumo por bebida antes de comprar."),
        ],
        extra_html="",
        cta_title="Empecemos tu menú hoy",
        cta_text="Escríbenos, cuéntanos tu idea de negocio y te ayudamos a armar la primera cotización sin compromiso.",
    ),
    dict(
        slug="siropes-para-cocteleria",
        catalog_href="siropes-bubble-tea/",
        catalog_label="Ver los 12 siropes",
        label="Bares y coctelería",
        title="Siropes para Bares y Coctelería en Colombia | Insumos Pop",
        metadesc="Siropes concentrados para cócteles, mocktails, sodas y limonadas. Doce sabores en botella de 1,9 L, precios con IVA y envíos en Colombia.",
        eyebrow="Para bares y coctelería",
        h1="Siropes para bares, coctelerías y bebidas sin alcohol",
        lead="Doce sabores concentrados en botella de 1,9 L. Con una dosis de 20 ml, el costo del sirope es de aproximadamente $1.158 por bebida y la botella alcanza para 95 preparaciones.",
        cta_label="Cotizar para mi barra",
        hero_product="siropes-de-fruta",
        wa_msg="Hola Insumos Pop 👋 Tengo un bar y quiero cotizar los siropes concentrados de 1.9 L para coctelería. ¿Qué sabores tienen disponibles y cómo funciona la muestra?",
        trust=[("Costo por copa calculable", "≈$1.158 con una dosis de 20 ml"),
               ("Dosis bajo tu control", "Rendimiento según tu receta"),
               ("12 sabores", "De lychee a manzana verde")],
        benefits=[
            ("Costo por copa que puedes calcular",
             "Botella de 1.9 L a $110.000: ≈$58 por ml. Tú decides el chorro y sabes tu costo exacto antes de armar el cóctel (la operación completa está abajo)."),
            ("Una referencia para varias secciones de la carta",
             "El mismo sabor puede usarse en cócteles, mocktails, sodas y limonadas. La dosis y la receta las controla tu barra."),
            ("12 sabores para toda la carta",
             "De lychee y maracuyá a manzana verde y toronja. Cotiza los sabores que necesitas con factura y ficha técnica."),
        ],
        product_slugs=["siropes-de-fruta", "polvo-coral-azul", "polvo-cheese-foam"],
        kit=dict(name="Kit para Barra",
                 pitch="Tres concentrados a elección para la carta de cócteles más el color insignia para el trago visual de la casa.",
                 items=[("siropes-de-fruta", 3, " — sabores a elección"), ("polvo-coral-azul", 1, None)]),
        menu_ideas=["Lychee martini", "Spritz de maracuyá", "Sour de manzana verde",
                    "Paloma con toronja", "Mocktail azul eléctrico", "Soda italiana"],
        recipe_slugs=["soda-italiana-con-sirope"],
        faqs=[
            ("¿Cuántos cócteles salen de una botella?",
             "Depende de la dosis. Con 20 ml por copa, una botella de 1,9 L rinde 95 preparaciones (1.900 ÷ 20); con 15 ml, unas 126. Prueba la receta y define el estándar de tu barra antes de calcular el rendimiento."),
            ("¿Sirven para mocktails y menú sin alcohol?",
             "Sí. Funcionan igual en soda italiana, limonada y té frío: la misma botella te cubre la carta con y sin alcohol."),
            ("¿Tienen factura y ficha técnica para mi control de proveedores?",
             "Facturamos como Taro Pop S.A.S. y al cotizar te entregamos la ficha técnica de cada sirope para tu control de insumos."),
        ],
        extra_html="""<div class="compare"><h3>Hagamos la cuenta juntos</h3>
<div class="trust" style="margin:6px 0 14px">
  <div><b>~$1.200</b>de sirope por cóctel (chorro de 20 ml)</div>
  <div><b>95</b>cócteles por botella de 1.9 L</div>
  <div><b>≈$58</b>por ml de concentrado</div>
</div>
<p class="muted">La derivación, para que la compruebes: botella de 1.9 L = 1.900 ml por $110.000 (IVA incluido) → $110.000 ÷ 1.900 ≈ $57,9 por ml. Un chorro de 20 ml × $57,9 ≈ $1.158, y 1.900 ÷ 20 = 95 copas. Con 15 ml: ≈$870 por copa y ~126 copas.</p>
<p class="muted">Es el costo del sirope, no del cóctel completo (licor, hielo, garnish y vaso van aparte). La dosis exacta la defines tú; por eso te damos muestra gratis antes de comprar.</p></div>""",
        cta_title="Haz la cuenta en tu barra",
        cta_text="Pide tu muestra, define tu chorro estándar y calcula tu costo por copa con datos reales.",
    ),
]
