# -*- coding: utf-8 -*-
"""Datos de productos Insumos Pop (fuente: Catalogo_Insumos_Pop_ES.pdf)."""

import os

WA = "573018656016"
WA_DISPLAY = "+57 301 8656016"

# Dominio del sitio. Se puede cambiar sin tocar el código:
#   - En local:  SITE_URL=https://otrodominio.com python3 build.py
#   - En CI:     definir la variable de entorno SITE_URL (ver README)
# Cuando migres a insumospop.com, solo cambias esa variable.
SITE = os.environ.get("SITE_URL", "https://taropop.co").rstrip("/")
DOMAIN = SITE.replace("https://", "").replace("http://", "")

POWDERS = [
    dict(
        slug="polvo-taro",
        name="Polvo de Taro",
        short="Taro",
        zh="芋頭",
        price=95000, format="Bolsa 1 kg", grams=1000,
        sku="IP-TARO-1K",
        img="polvo-taro-bubble-tea",
        alt="Bolsa negra de 1 kg de polvo de taro premium Insumos Pop junto a un plato con polvo violeta",
        origin="Taiwán",
        uses=["Milk tea", "Frappés", "Postres", "Helados"],
        teaser="El violeta hipnótico que detiene el scroll: cremoso, dulce y el alma de los milk teas más queridos de Asia.",
        desc=[
            "El taro es la raíz que conquistó Asia: cremosa, dulce y con ese violeta hipnótico que detiene el scroll. Cultivada por generaciones en el Lejano Oriente, es el alma de los milk teas más queridos del mundo.",
            "Con nuestro taro premium taiwanés, cada bebida tiene un color y un sabor que la versión local nunca logra: el que hace que el cliente vuelva por la foto y se quede por el sabor.",
        ],
        faqs=[
            ("¿El color violeta es natural del producto?",
             "Sí. El polvo entrega el tono violeta característico del taro sin necesidad de colorantes adicionales."),
            ("¿Sirve para bebidas frías y calientes?",
             "Sí. Funciona en milk tea frío o caliente, frappés licuados y bases para postre."),
        ],
        recipes=["bubble-tea-de-taro"],
        related=["polvo-okinawa-brown-sugar", "polvo-coral-azul", "polvo-hokkaido-milk-tea"],
    ),
    dict(
        slug="polvo-okinawa-brown-sugar",
        name="Okinawa Brown Sugar",
        short="Okinawa Brown Sugar",
        zh="黑糖",
        price=95000, format="Bolsa 1 kg", grams=1000,
        sku="IP-OKBS-1K",
        img="polvo-okinawa-brown-sugar",
        alt="Bolsa de 1 kg de polvo Okinawa Brown Sugar Insumos Pop con azúcar moreno en un plato",
        origin="Taiwán (estilo Okinawa, Japón)",
        uses=["Tiger sugar / milk tea", "Toppings", "Frappés", "Postres"],
        teaser="Caramelo profundo y tostado con notas de melaza: el corazón de la tendencia tiger sugar.",
        desc=[
            "En las islas de Okinawa, donde la gente vive más años que en cualquier otro lugar del planeta, el azúcar moreno es un tesoro. Caramelo profundo, tostado, con notas de melaza que envuelven la leche y la perla.",
            "Es el corazón de la tendencia tiger sugar que enloqueció a medio mundo: vetas doradas que bajan por el vaso y un dulzor que sabe a artesanía.",
        ],
        faqs=[
            ("¿Con este polvo logro el efecto de vetas del tiger sugar?",
             "Sí. Preparado como jarabe espeso permite marcar las vetas doradas en las paredes del vaso antes de servir la leche."),
            ("¿Reemplaza el azúcar de la receta?",
             "Aporta dulzor y sabor a la vez, así que normalmente reduce o reemplaza el endulzante de la bebida."),
        ],
        recipes=["brown-sugar-milk-tea"],
        related=["polvo-taro", "polvo-hokkaido-milk-tea", "polvo-thai-milk-tea"],
    ),
    dict(
        slug="polvo-matcha-taiwan",
        name="Taiwan Matcha",
        short="Matcha",
        zh="抹茶",
        price=95000, format="Bolsa 1 kg", grams=1000,
        sku="IP-MATT-1K",
        img="polvo-matcha-taiwan",
        alt="Bolsa de 1 kg de polvo Taiwan Matcha Insumos Pop con polvo verde intenso en un plato",
        origin="Taiwán",
        uses=["Matcha latte", "Frappés", "Repostería", "Helados"],
        teaser="Listo para crear el latte verde que todos quieren fotografiar: cremoso, herbal y elegante.",
        desc=[
            "Más que un color, una ceremonia. Nuestro matcha taiwanés viene listo para crear el latte verde que todos quieren fotografiar: cremoso, herbal, con ese amargor elegante que equilibra la dulzura.",
            "La ola verde ya llegó a Colombia: ofrécela con la calidad que la diferencia del polvo de supermercado.",
        ],
        faqs=[
            ("¿Cuál es la diferencia con el Shizuoka Matcha?",
             "Este es una mezcla lista para bebidas, pensada para servir rápido y con costo controlado. El Shizuoka Matcha es matcha 100% puro de origen japonés, para propuestas de autor."),
            ("¿Funciona en repostería?",
             "Sí. Aporta color y sabor a bizcochos, cheesecakes, cremas y helados."),
        ],
        recipes=["matcha-latte-frio"],
        related=["matcha-shizuoka", "polvo-hojicha", "polvo-cheese-foam"],
    ),
    dict(
        slug="matcha-shizuoka",
        name="Shizuoka Matcha 100% puro",
        short="Shizuoka Matcha",
        zh="静岡抹茶",
        price=110000, format="Bolsa 500 g", grams=500,
        sku="IP-MASH-500",
        img="matcha-shizuoka-puro",
        alt="Bolsa de 500 g de Shizuoka Matcha puro single origin de Insumos Pop con polvo verde en un plato",
        origin="Shizuoka, Japón (single origin)",
        uses=["Matcha de especialidad", "Lattes de autor", "Repostería premium"],
        teaser="Matcha puro de la región más venerada del té en Japón: hojas cultivadas a la sombra y molidas en piedra.",
        desc=[
            "De Shizuoka, la región más venerada del té en Japón, llega nuestro matcha puro de máxima calidad. Hojas cultivadas a la sombra y molidas en piedra hasta lograr un polvo verde intenso y sedoso, con un amargor noble que nunca raspa.",
            "Este no es un polvo para mezclar: es la materia prima de los baristas que quieren controlar cada gramo y cada sorbo. El matcha que sirves cuando quieres que el cliente sepa, desde el primer trago, que está tomando lo auténtico.",
        ],
        faqs=[
            ("¿Viene endulzado o con leche en polvo?",
             "No. Es matcha 100% puro single origin: tú controlas el endulzante, la leche y la intensidad."),
            ("¿Para qué tipo de negocio es ideal?",
             "Cafeterías de especialidad y barras que quieren un matcha de autor y una historia de origen real para su carta."),
        ],
        recipes=["matcha-latte-frio"],
        related=["polvo-matcha-taiwan", "hojicha-puro", "polvo-cheese-foam"],
    ),
    dict(
        slug="polvo-coral-azul",
        name="Coral Azul (Blue Coral)",
        short="Coral Azul",
        zh="藍珊瑚",
        price=95000, format="Bolsa 1 kg", grams=1000,
        sku="IP-CORAL-1K",
        img="polvo-coral-azul",
        alt="Bolsa de 1 kg de polvo Blue Coral de Insumos Pop con polvo azul eléctrico en un plato",
        origin="Taiwán",
        uses=["Bebidas visuales", "Limonadas y sodas", "Frappés", "Capas de color"],
        teaser="Un azul eléctrico que convierte cualquier bebida en un imán para las redes.",
        desc=[
            "El sabor que se ve antes de probarse. Un azul eléctrico que convierte cualquier bebida en un imán para las redes, el detalle que hace que tu local se vuelva “el del trago azul”.",
            "Refrescante y suave, es pura diversión visual: la bebida que los clientes piden solo para grabarla y terminan pidiendo otra.",
        ],
        faqs=[
            ("¿Con qué se combina mejor?",
             "Con bases lácteas, limonadas, sodas y frappés. También funciona en capas para bebidas de dos colores."),
            ("¿El color se mantiene en la bebida?",
             "Sí, entrega un azul estable ideal para fotos y video."),
        ],
        recipes=["soda-italiana-con-sirope"],
        related=["polvo-taro", "polvos-de-fruta", "siropes-de-fruta"],
    ),
    dict(
        slug="polvo-hojicha",
        name="Hojicha",
        short="Hojicha",
        zh="ほうじ茶",
        price=95000, format="Bolsa 1 kg", grams=1000,
        sku="IP-HOJI-1K",
        img="polvo-hojicha",
        alt="Bolsa de 1 kg de polvo Hojicha de Insumos Pop con polvo tostado color caramelo en un plato",
        origin="Taiwán (té verde tostado estilo Japón)",
        uses=["Hojicha latte", "Milk tea", "Frappés", "Postres"],
        teaser="Té verde tostado al fuego: menos amargo que el matcha, con notas cálidas a caramelo, nuez y madera.",
        desc=[
            "El secreto mejor guardado de Japón, y la próxima gran tendencia. El hojicha es té verde tostado al fuego: menos amargo que el matcha, con notas cálidas a caramelo, nuez y madera.",
            "Mientras todos pelean por el matcha, tú puedes ser el primero de tu ciudad en ofrecer “el nuevo matcha” y quedarte con la novedad antes que nadie.",
        ],
        faqs=[
            ("¿Sabe parecido al matcha?",
             "No: es más tostado y dulce en nariz, con menos amargor. Muchos clientes que no disfrutan el matcha aman el hojicha."),
            ("¿Cuál es la diferencia con el Pure Hojicha?",
             "Este es una mezcla lista para bebidas. El Pure Hojicha es té tostado 100% puro para recetas de autor."),
        ],
        recipes=["matcha-latte-frio"],
        related=["hojicha-puro", "polvo-matcha-taiwan", "polvo-hokkaido-milk-tea"],
    ),
    dict(
        slug="hojicha-puro",
        name="Pure Hojicha 100% puro",
        short="Pure Hojicha",
        zh="ほうじ茶",
        price=110000, format="Bolsa 500 g", grams=500,
        sku="IP-HOJP-500",
        img="hojicha-puro-japon",
        alt="Bolsa de 500 g de Pure Hojicha single origin de Insumos Pop con té tostado molido en un plato",
        origin="Japón (single origin)",
        uses=["Lattes de autor", "Postres premium", "Bebidas bajas en cafeína"],
        teaser="Té verde tostado de Japón en su forma más pura, con apenas una fracción de la cafeína del matcha.",
        desc=[
            "El té verde tostado de Japón, en su forma más pura: hojas tostadas lentamente al fuego hasta despertar sus notas a caramelo, nuez y madera, con apenas una fracción de la cafeína del matcha.",
            "Las empresas ganadoras ya lo saben: el hojicha es la próxima gran tendencia mundial, y casi nadie lo ofrece todavía en Colombia. Con nuestro hojicha puro, tu barista crea lattes y postres de autor con un sabor cálido e inconfundible, y tú te quedas con la moda que viene… antes que nadie.",
        ],
        faqs=[
            ("¿Tiene menos cafeína que el matcha?",
             "Sí, el hojicha contiene una fracción de la cafeína del matcha, ideal para cartas de tarde y noche."),
            ("¿Viene endulzado?",
             "No. Es té tostado 100% puro: tú defines leche, endulzante e intensidad."),
        ],
        recipes=["matcha-latte-frio"],
        related=["polvo-hojicha", "matcha-shizuoka", "polvo-okinawa-brown-sugar"],
    ),
    dict(
        slug="polvo-thai-milk-tea",
        name="Thai Milk Tea",
        short="Thai Milk Tea",
        zh="泰式奶茶",
        price=95000, format="Bolsa 1 kg", grams=1000,
        sku="IP-THAI-1K",
        img="polvo-thai-milk-tea",
        alt="Bolsa de 1 kg de polvo Thai Milk Tea de Insumos Pop con polvo naranja vibrante en un plato",
        origin="Taiwán (estilo Tailandia)",
        uses=["Thai tea frío", "Milk tea", "Frappés"],
        teaser="El clásico callejero de Bangkok: especiado, dulce y cremoso, con un naranja que ilumina la vitrina.",
        desc=[
            "Imposible olvidar ese naranja vibrante. El té tailandés es un clásico callejero de Bangkok: especiado, dulce y cremoso, con un color que ilumina la vitrina.",
            "Una bebida exótica, reconocible y adictiva que transporta al cliente a Asia sin salir de tu local.",
        ],
        faqs=[
            ("¿El color naranja es el característico del thai tea?",
             "Sí, entrega el tono naranja icónico del té tailandés tradicional."),
            ("¿Cómo se sirve tradicionalmente?",
             "Frío, con hielo y un toque de leche condensada o evaporada por encima."),
        ],
        recipes=["brown-sugar-milk-tea"],
        related=["polvo-hokkaido-milk-tea", "polvo-taro", "polvo-lemon-condensed-milk"],
    ),
    dict(
        slug="polvo-lemon-condensed-milk",
        name="Taiwan Lemon Condensed Milk",
        short="Lemon Condensed Milk",
        zh="檸檬煉乳",
        price=95000, format="Bolsa 1 kg", grams=1000,
        sku="IP-LEMON-1K",
        img="polvo-lemon-condensed-milk",
        alt="Bolsa de 1 kg de polvo Lemon Condensed Milk de Insumos Pop con polvo amarillo suave en un plato",
        origin="Taiwán",
        uses=["Bebidas cítricas", "Frappés", "Limonadas cremosas"],
        teaser="El brillo cítrico del limón con la caricia de la leche condensada: contraste que engancha desde el primer sorbo.",
        desc=[
            "El equilibrio perfecto entre lo ácido y lo dulce. Inspirado en las bebidas de los mercados de Taiwán, une el brillo cítrico del limón con la caricia de la leche condensada.",
            "Refrescante y goloso a la vez: ese contraste que sorprende y engancha desde el primer sorbo.",
        ],
        faqs=[
            ("¿Es muy ácido?",
             "No: el perfil es equilibrado, con la cremosidad de la leche condensada suavizando el cítrico."),
            ("¿En qué bebidas funciona mejor?",
             "Limonadas cremosas, frappés y tés fríos con un giro diferente."),
        ],
        recipes=["soda-italiana-con-sirope"],
        related=["polvo-mango-coco-hong-kong", "polvos-de-fruta", "polvo-coral-azul"],
    ),
    dict(
        slug="polvo-hokkaido-milk-tea",
        name="Hokkaido Milk Tea",
        short="Hokkaido Milk Tea",
        zh="北海道奶茶",
        price=95000, format="Bolsa 1 kg", grams=1000,
        sku="IP-HOKK-1K",
        img="polvo-hokkaido-milk-tea",
        alt="Bolsa de 1 kg de polvo Hokkaido Milk Tea de Insumos Pop con polvo cremoso en un plato",
        origin="Taiwán (estilo Hokkaido, Japón)",
        uses=["Milk tea", "Bebidas calientes", "Frappés"],
        teaser="Suave, lácteo y reconfortante como un abrazo tibio: puro confort cremoso con sello japonés.",
        desc=[
            "Hokkaido es sinónimo de la mejor leche de Japón, y este milk tea lo celebra: suave, lácteo y reconfortante, como un abrazo tibio.",
            "Sin estridencias, puro confort cremoso: el sabor que conquista al cliente que busca algo delicioso y familiar, con sello japonés.",
        ],
        faqs=[
            ("¿Es un buen sabor para empezar mi carta?",
             "Sí: es el perfil más familiar y fácil de vender de los milk teas, ideal como puerta de entrada."),
            ("¿Funciona caliente?",
             "Muy bien: es de los sabores que mejor se comporta en carta de bebidas calientes."),
        ],
        recipes=["brown-sugar-milk-tea"],
        related=["polvo-okinawa-brown-sugar", "polvo-thai-milk-tea", "polvo-taro"],
    ),
    dict(
        slug="polvo-mango-coco-hong-kong",
        name="Hong Kong Mango Coconut",
        short="Mango Coconut",
        zh="芒果椰子",
        price=95000, format="Bolsa 1 kg", grams=1000,
        sku="IP-HKMC-1K",
        img="polvo-mango-coco-hong-kong",
        alt="Bolsa de 1 kg de polvo Hong Kong Mango Coconut de Insumos Pop con polvo dorado en un plato",
        origin="Taiwán (estilo Hong Kong)",
        uses=["Frappés", "Smoothies", "Postres tropicales"],
        teaser="Mango maduro y coco cremoso en una bebida tropical que sabe a vacaciones.",
        desc=[
            "Un pedazo de trópico con acento de Hong Kong. Mango maduro y coco cremoso se funden en una bebida tropical, dulce y exótica que sabe a vacaciones.",
            "El sabor que se vende solo en clima cálido: perfecto para frappés, smoothies y postres que piden verano.",
        ],
        faqs=[
            ("¿Sirve para smoothies con fruta natural?",
             "Sí: potencia el sabor y da cuerpo cremoso a smoothies con fruta fresca o congelada."),
            ("¿Qué toppings le van bien?",
             "Perlas de tapioca, jellies de coco o mango y espuma de queso."),
        ],
        recipes=["soda-italiana-con-sirope"],
        related=["polvos-de-fruta", "polvo-lemon-condensed-milk", "siropes-de-fruta"],
    ),
    dict(
        slug="polvo-cheese-foam",
        name="Taiwan Cheese Foam",
        short="Cheese Foam",
        zh="芝士奶蓋",
        price=95000, format="Bolsa 1 kg", grams=1000,
        sku="IP-CHFO-1K",
        img="polvo-cheese-foam",
        alt="Bolsa de 1 kg de polvo Cheese Foam de Insumos Pop con polvo claro en un plato",
        origin="Taiwán",
        uses=["Topping de bebidas", "Té frío", "Café frío", "Frappés"],
        teaser="La corona que lo cambia todo: espuma cremosa de queso, dulce con un toque salado.",
        desc=[
            "La corona que lo cambia todo. Una espuma cremosa de queso, dulce con un toque salado, que se sirve sobre el té o el café frío y crea ese contraste irresistible.",
            "Es la tendencia que arrasa en Asia y que casi nadie tiene aquí: la capa premium que te deja cobrar más por vaso y que el cliente no encuentra en ninguna otra parte.",
        ],
        faqs=[
            ("¿Sobre qué bebidas se sirve?",
             "Sobre té frío (verde, negro, de fruta), café frío, matcha y milk teas. Se sirve como capa superior."),
            ("¿Necesito equipo especial?",
             "Solo batidora o shaker: la espuma se logra batiendo el polvo con leche fría."),
        ],
        recipes=["matcha-latte-frio"],
        related=["polvo-matcha-taiwan", "polvo-okinawa-brown-sugar", "polvo-taro"],
    ),
]

FRUIT_POWDER = dict(
    slug="polvos-de-fruta",
    name="Polvos de Fruta — Sabores Asiáticos",
    short="Polvos de Fruta",
    zh="果粉",
    price=65000, format="Bolsa 1 kg", grams=1000,
    sku="IP-FRUTA-1K",
    img="polvos-de-fruta-linea",
    img2="polvos-de-fruta-sabores",
    alt="Línea de polvos de fruta Insumos Pop: bolsas blancas de mango, fresa, coco y sandía de 1 kg",
    alt2="Bolsas de polvos de fruta de Insumos Pop en sabores mango, fresa, coco y sandía",
    origin="Asia (importación directa)",
    flavors=["Mango", "Fresa", "Coco", "Banana", "Sandía", "Aguacate"],
    uses=["Frappés", "Smoothies", "Milk tea de fruta", "Postres"],
    teaser="Los sabores que tu cliente ya pide, con el perfil limpio y aromático de la fruta asiática. 6 sabores, $65.000 el kilo.",
    desc=[
        "Hay frutas que todos conocen, y luego está la versión asiática. En los huertos del Lejano Oriente la fruta se cultiva con una obsesión por el sabor que se siente en cada sorbo: notas más limpias, dulces y aromáticas que las mezclas corrientes.",
        "Son los sabores que tu cliente ya pide, pero con un trasfondo que los vuelve memorables: la forma más sencilla de completar tu carta, con calidad premium a un precio accesible.",
    ],
    faqs=[
        ("¿Puedo pedir varios sabores en un mismo pedido?",
         "Claro: arma tu cotización con los sabores que necesites; cada bolsa de 1 kg cuesta $65.000 con IVA incluido."),
        ("¿Qué sabores hay disponibles?",
         "Mango, Fresa, Coco, Banana, Sandía y Aguacate."),
    ],
    recipes=["soda-italiana-con-sirope"],
    related=["siropes-de-fruta", "polvo-mango-coco-hong-kong", "polvo-coral-azul"],
)

SYRUP = dict(
    slug="siropes-de-fruta",
    name="Siropes de Fruta — Concentrados Asiáticos",
    short="Siropes de Fruta",
    zh="果露",
    price=110000, format="Botella 1.9 L", grams=None,
    sku="IP-SIROPE-19L",
    img="siropes-de-fruta-linea",
    img2="sirope-melocoton",
    img3="siropes-sabores",
    alt="Línea de siropes de fruta Insumos Pop en botellas de 1.9 litros",
    alt2="Botella de sirope de melocotón de Insumos Pop de 1.9 litros",
    alt3="Botellas de sirope de fruta Insumos Pop de 1.9 litros en varios sabores",
    origin="Taiwán",
    flavors=["Mango", "Maracuyá", "Fresa", "Lychee", "Melocotón", "Piña",
             "Arándano", "Limón", "Naranja", "Toronja", "Cereza", "Manzana Verde"],
    uses=["Cócteles", "Frappés", "Lattes", "Limonadas", "Sodas italianas", "Té de frutas"],
    teaser="Concentrados de fruta nacidos en Taiwán: un solo chorro transforma cualquier bebida. 12 sabores, botella de 1.9 L.",
    desc=[
        "El secreto de una bebida que enamora casi siempre está en un buen sirope. Los nuestros nacen en Taiwán, donde la fruta se trabaja con cuidado y precisión hasta lograr un sabor intenso, limpio y natural, sin el gusto artificial de los jarabes comunes.",
        "Un solo chorro transforma un cóctel, un frappé, un latte, una limonada o una soda italiana en algo que el cliente recuerda y vuelve a pedir. Son concentrados de verdad: rinden muchísimo, así que tu carta gana sabor y tú cuidas el margen.",
    ],
    faqs=[
        ("¿Cuántos sabores puedo combinar en un pedido?",
         "Los que quieras: arma tu cotización con los sabores que necesita tu barra."),
        ("¿Sirven para coctelería?",
         "Sí: son concentrados aptos para cóctel, mocktail, soda italiana, limonada, frappé, latte y té de frutas."),
    ],
    recipes=["soda-italiana-con-sirope"],
    related=["polvos-de-fruta", "polvo-coral-azul", "polvo-mango-coco-hong-kong"],
)

RECIPES = [
    dict(
        slug="bubble-tea-de-taro",
        title="Bubble tea de taro clásico",
        metadesc="Receta sugerida de bubble tea de taro paso a paso para tu negocio: base de té, polvo de taro premium y perlas de tapioca.",
        intro="El milk tea violeta que todo el mundo fotografía. Esta es la receta base para un vaso grande; ajusta dosis y dulzor a tu vaso, tu leche y tu costo por bebida.",
        uses=["polvo-taro"],
        ingredients=[
            "Polvo de Taro Insumos Pop (dosis sugerida: 2–3 cucharadas, ajusta a tu receta)",
            "200 ml de té negro o de jazmín preparado y frío",
            "150 ml de leche entera o bebida vegetal",
            "Hielo al gusto",
            "Perlas de tapioca cocidas",
            "Endulzante al gusto (opcional: el taro ya aporta dulzor)",
        ],
        steps=[
            "Cocina las perlas de tapioca y resérvalas en almíbar para que no se peguen.",
            "En shaker o licuadora, mezcla el té frío, la leche y el polvo de taro hasta disolver por completo.",
            "Prueba y ajusta dulzor. La bebida debe quedar cremosa y de color violeta uniforme.",
            "Sirve las perlas en el vaso, agrega hielo y vierte la mezcla de taro.",
            "Cierra con tapa de cúpula o sella, entrega con pitillo grueso y lista para la foto.",
        ],
        tip="Para versión frappé, licúa la misma mezcla con el hielo y sirve con las perlas al fondo.",
    ),
    dict(
        slug="brown-sugar-milk-tea",
        title="Brown sugar milk tea estilo tigre",
        metadesc="Receta sugerida de brown sugar milk tea (tiger sugar) con vetas doradas, usando polvo Okinawa Brown Sugar.",
        intro="La bebida de las vetas doradas. El secreto está en preparar un jarabe espeso de brown sugar y pintar las paredes del vaso antes de servir la leche.",
        uses=["polvo-okinawa-brown-sugar"],
        ingredients=[
            "Polvo Okinawa Brown Sugar Insumos Pop (para el jarabe: disuelto en un poco de agua caliente hasta espesar)",
            "250 ml de leche entera bien fría",
            "Perlas de tapioca cocidas",
            "Hielo al gusto",
            "Opcional: shot de té negro concentrado",
        ],
        steps=[
            "Prepara un jarabe espeso disolviendo el polvo de brown sugar en muy poca agua caliente.",
            "Mezcla las perlas calientes con parte del jarabe para glasearlas.",
            "Con una cuchara, pinta vetas de jarabe en las paredes internas del vaso.",
            "Agrega las perlas glaseadas, el hielo y vierte la leche fría lentamente.",
            "Sirve sin mezclar: las vetas de tigre hacen el show cuando el cliente revuelve.",
        ],
        tip="Sirve inmediatamente después de pintar el vaso para que las vetas se mantengan definidas.",
    ),
    dict(
        slug="matcha-latte-frio",
        title="Matcha latte frío (y su versión hojicha)",
        metadesc="Receta sugerida de matcha latte frío con matcha taiwanés o Shizuoka puro, y variante de hojicha latte.",
        intro="El latte verde que todos quieren fotografiar, en dos niveles: mezcla lista para servicio rápido o matcha puro para carta de especialidad. La misma técnica sirve para el hojicha latte.",
        uses=["polvo-matcha-taiwan", "matcha-shizuoka", "polvo-hojicha", "hojicha-puro"],
        ingredients=[
            "Taiwan Matcha Insumos Pop (mezcla lista) o Shizuoka Matcha 100% puro (dosifica según intensidad deseada)",
            "200 ml de leche fría (entera o vegetal)",
            "60 ml de agua caliente (si usas matcha puro, para activar el té)",
            "Endulzante al gusto (el matcha puro no viene endulzado)",
            "Hielo",
        ],
        steps=[
            "Si usas matcha puro: bátelo con el agua caliente (batidor de bambú o eléctrico) hasta que no queden grumos.",
            "Si usas la mezcla lista: disuélvela directamente en un poco de leche.",
            "Llena el vaso con hielo y vierte la leche fría.",
            "Corona vertiendo el matcha por encima para lograr el degradé verde.",
            "Opcional: termina con espuma de queso Cheese Foam para la versión premium.",
        ],
        tip="Cambia el matcha por Hojicha o Pure Hojicha y tienes el 'latte tostado' que casi nadie ofrece todavía en Colombia.",
    ),
    dict(
        slug="soda-italiana-con-sirope",
        title="Soda italiana y limonada con siropes de fruta",
        metadesc="Receta sugerida de soda italiana y limonada con siropes concentrados de fruta asiáticos: lychee, maracuyá, melocotón y más.",
        intro="La forma más rápida de sumar color y sabor a tu carta: soda + hielo + un chorro de sirope concentrado. Funciona igual con limonada, té frío o cóctel.",
        uses=["siropes-de-fruta", "polvos-de-fruta", "polvo-coral-azul"],
        ingredients=[
            "Sirope de fruta Insumos Pop del sabor que quieras (lychee, maracuyá, melocotón, manzana verde…)",
            "Soda o agua con gas bien fría",
            "Hielo",
            "Opcional: jugo de limón, fruta fresca o jellies para decorar",
        ],
        steps=[
            "Llena el vaso con hielo.",
            "Agrega un chorro generoso de sirope al fondo (los concentrados rinden: empieza con poco y ajusta).",
            "Completa con soda fría y decora con fruta o hierbabuena.",
            "Sirve con pitillo y mezcla frente al cliente: el degradé de color es parte del show.",
            "Para limonada: reemplaza la soda por limonada natural. Para el 'trago azul', suma un toque de Coral Azul.",
        ],
        tip="Marca en tu carta los sabores de temporada y rota los siropes para mantener la novedad.",
    ),
]

# ---------------------------------------------------------------- landings por perfil
PROFILES = [
    dict(
        slug="proveedor-bubble-tea",
        catalog_href="polvos-bubble-tea/",
        catalog_label="Ver los polvos",
        label="Tiendas de bubble tea",
        title="Proveedor de insumos para tiendas de bubble tea | Importación directa | Insumos Pop",
        metadesc="Polvos y siropes premium importados directo de Taiwán para tiendas de bubble tea en Colombia: taro, brown sugar, thai tea y más. Precio de importador con IVA, ficha técnica y muestra gratis. Cotiza por WhatsApp.",
        eyebrow="Para tiendas de bubble tea",
        h1="El sabor original de Taiwán, directo a tu barra",
        lead="Importamos los mismos polvos premium que usan las tiendas de bubble tea en Asia. Precio de importador, ficha técnica y muestra gratis para tu negocio.",
        cta_label="Cotizar por WhatsApp",
        hero_product="polvo-okinawa-brown-sugar",
        wa_msg="Hola Insumos Pop 👋 Tengo una tienda de bubble tea y quiero cotizar los polvos premium de Taiwán. ¿Me comparten precios por volumen y la muestra gratis?",
        trust=[("Importación directa", "De la fábrica en Taiwán a tu local"),
               ("Costo por bebida claro", "Costo por gramo en cada ficha"),
               ("Muestra gratis", "Compara contra tu polvo actual")],
        benefits=[
            ("Importación directa de Taiwán",
             "Sin intermediarios: compras al importador (con factura, Taro Pop S.A.S.) los insumos que definieron el bubble tea en su país de origen."),
            ("Costo por bebida bajo control",
             "Bolsas de 1 kg a $95.000: cada ficha muestra el costo por gramo para que calcules tu margen por vaso antes de comprar."),
            ("Pruébalo antes de comprar",
             "Muestra gratis para negocios y asesoría directa: compara color, aroma y disolución contra tu insumo actual con tu propia receta."),
        ],
        product_slugs=["polvo-taro", "polvo-okinawa-brown-sugar", "polvo-thai-milk-tea",
                       "polvo-hokkaido-milk-tea", "polvo-cheese-foam", "polvo-coral-azul"],
        kit=dict(name="Kit Sabores de Taiwán",
                 pitch="Los tres milk teas más pedidos de Asia más el topping que sube el ticket por vaso.",
                 items=[("polvo-taro", 1, None), ("polvo-okinawa-brown-sugar", 1, None),
                        ("polvo-thai-milk-tea", 1, None), ("polvo-cheese-foam", 1, None)]),
        menu_ideas=["Taro milk tea", "Tiger brown sugar", "Thai tea frío", "Hokkaido clásico",
                    "La bebida azul viral", "Té frío + cheese foam"],
        recipe_slugs=["bubble-tea-de-taro", "brown-sugar-milk-tea"],
        faqs=[
            ("¿En qué se diferencia de los polvos que ya uso?",
             "Son importados directamente de Taiwán, el país donde nació el bubble tea. Te enviamos muestra gratis para que compares color, aroma y disolución contra tu insumo actual con tu propia receta: la prueba la haces tú."),
            ("¿Cuánto rinde una bolsa de 1 kg?",
             "Depende de tu dosis por vaso. Cada ficha incluye el costo por gramo (a $95.000 el kilo, $95 por gramo) para que calcules el rendimiento exacto con tu receta, y al cotizar te compartimos la ficha técnica con dosificación."),
            ("¿Venden perlas de tapioca o vasos?",
             "Por ahora nuestro catálogo se concentra en polvos, puros y siropes. Al cotizar te asesoramos sobre cómo integrarlos con los demás insumos de tu operación."),
        ],
        extra_html="",
        cta_title="¿Listo para que tu barra sepa a Taiwán?",
        cta_text="Pide tu muestra gratis, compárala con tu insumo actual y decide con tu propia receta.",
    ),
    dict(
        slug="bubble-tea-para-cafeterias",
        catalog_href="polvos-bubble-tea/",
        catalog_label="Ver el catálogo",
        label="Cafeterías",
        title="Bubble tea y matcha para cafeterías | Suma una línea nueva | Insumos Pop",
        metadesc="Agrega milk teas, matcha, hojicha y cheese foam a la carta de tu cafetería sin sobre-invertir: insumos premium de Taiwán y Japón, ficha técnica con dosificación y asesoría por WhatsApp en Colombia.",
        eyebrow="Para cafeterías",
        h1="Los sabores que tu ciudad todavía no conoce",
        lead="Matcha de Shizuoka, hojicha, cheese foam: insumos de especialidad importados directo de Asia para que tu carta no se parezca a ninguna otra. Muestra gratis para tu cafetería.",
        cta_label="Pedir muestra y cotizar",
        hero_product="matcha-shizuoka",
        wa_msg="Hola Insumos Pop 👋 Tengo una cafetería y quiero diferenciar mi carta con matcha, hojicha y cheese foam. ¿Me envían cotización y muestra gratis?",
        trust=[("Origen real", "Single origin de Japón y Taiwán"),
               ("Dos niveles", "Mezclas listas y puros de autor"),
               ("Asesoría directa", "Ficha técnica y dosificación al cotizar")],
        benefits=[
            ("Origen que puedes contar",
             "Shizuoka Matcha y Pure Hojicha son single origin de Japón: una historia real para tu carta, no un polvo genérico de proveedor local."),
            ("Dos niveles para tu operación",
             "Mezclas listas ($95.000/kg) para servicio rápido y puros ($110.000/500 g) para bebidas de autor: tú eliges margen y posicionamiento."),
            ("Un topping que nadie más tiene",
             "La corona de cheese foam sobre café o té frío es un upgrade visible que te permite cobrar más por vaso, y casi ninguna cafetería en Colombia la ofrece."),
        ],
        product_slugs=["matcha-shizuoka", "hojicha-puro", "polvo-matcha-taiwan",
                       "polvo-hojicha", "polvo-cheese-foam", "siropes-de-fruta"],
        kit=dict(name="Kit Barra de Especialidad",
                 pitch="Dos puros de origen japonés para bebidas de autor más el topping que corona la versión premium.",
                 items=[("matcha-shizuoka", 1, None), ("hojicha-puro", 1, None),
                        ("polvo-cheese-foam", 1, None)]),
        menu_ideas=["Matcha latte de autor", "Hojicha latte", "Dirty matcha", "Café frío con cheese foam",
                    "Soda italiana de temporada", "Matcha tonic"],
        recipe_slugs=["matcha-latte-frio", "soda-italiana-con-sirope"],
        faqs=[
            ("¿Cuál me conviene: el Taiwan Matcha o el Shizuoka puro?",
             "El Taiwan Matcha es mezcla lista: rápido y de costo controlado. El Shizuoka es matcha 100% puro sin endulzar, para carta de especialidad donde tú controlas leche, dulzor e intensidad. Muchas cafeterías usan los dos en niveles de precio distintos."),
            ("¿Mi barista necesita capacitación o equipo especial?",
             "No. Las mezclas se disuelven en leche; el matcha puro se bate con agua caliente (batidor de bambú o eléctrico) y el cheese foam se logra con batidora o shaker. Al cotizar te damos asesoría directa y ficha técnica."),
            ("¿Estas bebidas son moda pasajera?",
             "Nadie puede garantizarte ventas, y no lo vamos a hacer. Lo que sí es un dato: firmas de investigación proyectan crecimiento global sostenido de la categoría (~7–9% anual), y en Colombia la oferta todavía es escasa: llegar temprano es la ventaja."),
        ],
        extra_html="""<div class="compare"><h3>La ola apenas llega a Colombia</h3>
<p>Firmas de investigación de mercado — <strong>Grand View Research</strong>, <strong>IMARC</strong> y <strong>Fortune Business Insights</strong> — proyectan que el mercado global de bubble tea crecerá entre 7% y 9% anual en los próximos años.</p>
<p class="muted">Es un dato global — no una promesa sobre tu ciudad —, pero dice algo claro: la categoría va en una sola dirección, y en Colombia casi nadie la está atendiendo todavía. Llegar temprano es la ventaja.</p></div>""",
        cta_title="Sé el primero de tu ciudad",
        cta_text="Pide tu muestra gratis de matcha, hojicha o cheese foam y pruébala en tu propia barra antes de decidir.",
    ),
    dict(
        slug="kit-emprendedor-bubble-tea",
        catalog_href="guia-emprender-bubble-tea/",
        catalog_label="Leer la guía para emprender",
        label="Emprendedores",
        title="Kit para emprender con bubble tea en Colombia | Todo para empezar | Insumos Pop",
        metadesc="¿Vas a montar tu primer negocio de bebidas? Kit inicial con los polvos y siropes que sí rotan, recetas base, costo por gramo en cada ficha y un asesor real por WhatsApp. Envíos a toda Colombia y muestra gratis.",
        eyebrow="Para tu primer negocio",
        h1="Tu primer menú de bebidas, sin adivinar",
        lead="Te asesoramos gratis para armar una carta que funcione desde el día uno: sabores probados, costo por gramo en cada ficha y muestra antes de comprar.",
        cta_label="Empezar con asesoría gratis",
        hero_product="polvo-taro",
        wa_msg="Hola Insumos Pop 👋 Estoy montando mi primer negocio de bebidas y quiero asesoría para armar mi menú inicial. ¿Me ayudan con la cotización del Kit Primer Menú?",
        trust=[("Costos claros", "Costo por gramo antes de invertir"),
               ("Asesoría real", "Un asesor directo por WhatsApp"),
               ("Riesgo mínimo", "Muestra gratis y factura legal")],
        benefits=[
            ("Costos claros antes de invertir",
             "Cada ficha muestra el costo por gramo: sabes cuánto te cuesta cada bebida antes de comprar la primera bolsa."),
            ("Asesoría directa, no solo venta",
             "Te acompañamos a elegir sabores, dosis y recetas para tu primer menú; además tienes la guía para emprender y 4 recetas paso a paso en el sitio."),
            ("Riesgo mínimo para arrancar",
             "Muestra gratis para negocios, factura legal (Taro Pop S.A.S.) y un kit inicial ya armado con los sabores más fáciles de vender."),
        ],
        product_slugs=["polvo-taro", "polvo-hokkaido-milk-tea", "polvo-matcha-taiwan",
                       "siropes-de-fruta", "polvos-de-fruta"],
        kit=dict(name="Kit Primer Menú",
                 pitch="Los 3 polvos con los que arranca un menú que rota, más 2 siropes para limonadas y sodas. Con esto montas una carta inicial de 5+ bebidas usando las recetas del sitio.",
                 items=[("polvo-taro", 1, None), ("polvo-hokkaido-milk-tea", 1, None),
                        ("polvo-matcha-taiwan", 1, None), ("siropes-de-fruta", 2, " — sabores a elección")]),
        menu_ideas=["Taro milk tea", "Milk tea clásico", "Matcha latte frío",
                    "Limonada de sabores", "Soda italiana"],
        recipe_slugs=["bubble-tea-de-taro", "matcha-latte-frio"],
        faqs=[
            ("¿Cuánto necesito para empezar?",
             "El Kit Primer Menú cuesta $505.000 con IVA incluido y te da 3 kilos de polvos premium más 2 siropes de 1.9 L: suficiente para lanzar una carta inicial. También puedes cotizar productos sueltos desde $65.000."),
            ("No sé nada de bubble tea, ¿me van a dejar solo?",
             "No. Al cotizar recibes asesoría directa y ficha técnica de cada producto, y en el sitio tienes la guía para emprender y 4 recetas paso a paso con dosis sugeridas."),
            ("¿Me garantizan que el negocio va a funcionar?",
             "No, y desconfía de quien te lo garantice. Lo que sí te garantizamos: insumos importados directo de Taiwán, precios claros con IVA, muestra gratis para probar antes de invertir y acompañamiento para que tu costeo por bebida sea realista desde el día uno."),
        ],
        extra_html="",
        cta_title="Empecemos tu menú hoy",
        cta_text="Escríbenos, cuéntanos tu idea de negocio y te ayudamos a armar la primera cotización sin compromiso.",
    ),
    dict(
        slug="siropes-para-cocteleria",
        catalog_href="siropes-bubble-tea/",
        catalog_label="Ver los 12 siropes",
        label="Bares y coctelería",
        title="Siropes de fruta para bares y coctelería | 12 sabores | Insumos Pop",
        metadesc="Siropes taiwaneses concentrados para cócteles, mocktails y sodas italianas: lychee, maracuyá, toronja y 9 sabores más. Botella de 1.9 L que rinde y cuida tu margen. Cotiza por WhatsApp para tu bar en Colombia.",
        eyebrow="Para bares y coctelería",
        h1="Siropes de Taiwán para cócteles que se recuerdan",
        lead="12 concentrados de fruta con sabor limpio e intenso, en botella de 1.9 L. Haz la cuenta: con un chorro de 20 ml, el sirope de tu cóctel cuesta alrededor de $1.200.",
        cta_label="Cotizar para mi barra",
        hero_product="siropes-de-fruta",
        wa_msg="Hola Insumos Pop 👋 Tengo un bar y quiero cotizar los siropes concentrados de 1.9 L para coctelería. ¿Qué sabores tienen disponibles y cómo funciona la muestra?",
        trust=[("Costo por copa claro", "≈$1.200 de sirope por cóctel de 20 ml"),
               ("Concentrado real", "Rinde según la dosis que tú defines"),
               ("12 sabores", "De lychee a manzana verde")],
        benefits=[
            ("Costo por copa que puedes calcular",
             "Botella de 1.9 L a $110.000: ≈$58 por ml. Tú decides el chorro y sabes tu costo exacto antes de armar el cóctel (la operación completa está abajo)."),
            ("Concentrado real, no jarabe aguado",
             "Son concentrados de fruta hechos en Taiwán: un chorro transforma un cóctel, un mocktail o una soda, y la dosis la controlas tú."),
            ("12 sabores para toda la carta",
             "De lychee y maracuyá a manzana verde y toronja: clásicos y sabores asiáticos que tu competencia difícilmente tiene, con factura y ficha técnica."),
        ],
        product_slugs=["siropes-de-fruta", "polvo-coral-azul", "polvo-cheese-foam"],
        kit=dict(name="Kit Barra Premium",
                 pitch="Tres concentrados a elección para la carta de cócteles más el color insignia para el trago visual de la casa.",
                 items=[("siropes-de-fruta", 3, " — sabores a elección"), ("polvo-coral-azul", 1, None)]),
        menu_ideas=["Lychee martini", "Spritz de maracuyá", "Sour de manzana verde",
                    "Paloma con toronja", "Mocktail azul eléctrico", "Soda italiana premium"],
        recipe_slugs=["soda-italiana-con-sirope"],
        faqs=[
            ("¿Cuántos cócteles salen de una botella?",
             "Depende del chorro que definas. Con 20 ml por copa, una botella de 1.9 L rinde 95 copas (1.900 ÷ 20); con 15 ml, unas 126. Al ser concentrado, la dosis suele ser menor que con jarabes comunes: pruébalo con la muestra gratis y define tu estándar."),
            ("¿Sirven para mocktails y menú sin alcohol?",
             "Sí. Funcionan igual en soda italiana, limonada y té frío: la misma botella te cubre la carta con y sin alcohol."),
            ("¿Tienen factura y ficha técnica para mi control de proveedores?",
             "Facturamos como Taro Pop S.A.S. y al cotizar te entregamos la ficha técnica de cada sirope para tu control de insumos."),
        ],
        extra_html="""<div class="compare"><h3>Hagamos la cuenta juntos</h3>
<div class="trust" style="margin:6px 0 14px">
  <div><b>~$1.200</b>de sirope por cóctel (chorro de 20 ml)</div>
  <div><b>95</b>cócteles por botella de 1.9 L</div>
  <div><b>≈$58</b>por ml de concentrado</div>
</div>
<p class="muted">La derivación, para que la compruebes: botella de 1.9 L = 1.900 ml por $110.000 (IVA incluido) → $110.000 ÷ 1.900 ≈ $57,9 por ml. Un chorro de 20 ml × $57,9 ≈ $1.158, y 1.900 ÷ 20 = 95 copas. Con 15 ml: ≈$870 por copa y ~126 copas.</p>
<p class="muted">Es el costo del sirope, no del cóctel completo (licor, hielo, garnish y vaso van aparte). La dosis exacta la defines tú; por eso te damos muestra gratis antes de comprar.</p></div>""",
        cta_title="Haz la cuenta en tu barra",
        cta_text="Pide tu muestra, define tu chorro estándar y calcula tu costo por copa con datos reales.",
    ),
]
